[package]
name = "sledoview"
version = "1.1.0"
edition = "2021"
authors = ["Gregory Chris <sgchris@gmail.com>"]
description = "A CLI tool for viewing and managing SLED database files"
license = "MIT"
repository = "https://github.com/sgchris/sledoview"
readme = "README.md"
keywords = ["sled", "database", "cli", "viewer"]
categories = ["command-line-utilities", "database"]
homepage = "https://sledoview.greq.me/"

[package.metadata.wix]
upgrade-guid = "3F6DF45D-26A3-4B8D-BEDD-0573A0F488C5"
path-guid = "EA5739B2-6265-4AB7-AC1B-0A9DACCB2485"
license = false
eula = false

[[bin]]
name = "sledoview"
path = "src/main.rs"

[lib]
name = "sledoview"
path = "src/lib.rs"

[dependencies]
sled = "0.34"
clap = { version = "4", features = ["derive"] }
colored = "3"
anyhow = "1"
rustyline = "15"
rustyline-derive = "0.11"
regex = "1"
glob = "0.3"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
